/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.twitter.sdk.android.core;

public final class R {
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int contentDescriptionOff=0x7f010003;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int contentDescriptionOn=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int dgts__StateButtonStyle=0x7f010010;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static int dgts__accentColor=0x7f01000b;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int dgts__logoDrawable=0x7f01000c;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int finishStateText=0x7f01000d;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int progressStateText=0x7f01000e;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int startStateText=0x7f01000f;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int state_toggled_on=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int toggleOnClick=0x7f010004;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tw__action_color=0x7f010008;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tw__action_highlight_color=0x7f010009;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tw__container_bg_color=0x7f010006;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tw__image_aspect_ratio=0x7f01002c;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>height</code></td><td>0</td><td></td></tr>
<tr><td><code>width</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int tw__image_dimension_to_adjust=0x7f01002d;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tw__primary_text_color=0x7f010007;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tw__tweet_actions_enabled=0x7f01000a;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int tw__tweet_id=0x7f010005;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int tw__twitter_logo=0x7f010000;
    }
    public static final class color {
        public static int dgts__default_accent=0x7f070011;
        public static int dgts__default_logo_name=0x7f070012;
        public static int dgts__purple=0x7f070013;
        public static int dgts__purple_pressed=0x7f070014;
        public static int dgts__text_dark=0x7f070015;
        public static int dgts__text_light=0x7f070016;
        public static int tw__blue_default=0x7f07004d;
        public static int tw__blue_pressed=0x7f07004e;
        public static int tw__blue_pressed_light=0x7f07004f;
        public static int tw__composer_black=0x7f070000;
        public static int tw__composer_blue=0x7f070001;
        public static int tw__composer_blue_text=0x7f070002;
        public static int tw__composer_deep_gray=0x7f070003;
        public static int tw__composer_light_gray=0x7f070004;
        public static int tw__composer_red=0x7f070005;
        public static int tw__composer_white=0x7f070006;
        public static int tw__light_gray=0x7f070050;
        public static int tw__medium_gray=0x7f070051;
        public static int tw__seekbar_thumb_inner_color=0x7f070007;
        public static int tw__seekbar_thumb_outer_color=0x7f070008;
        public static int tw__solid_white=0x7f070052;
        public static int tw__transparent=0x7f070053;
        public static int tw__tweet_action_color=0x7f070009;
        public static int tw__tweet_action_dark_highlight_color=0x7f07000a;
        public static int tw__tweet_action_light_highlight_color=0x7f07000b;
        public static int tw__tweet_dark_container_bg_color=0x7f07000c;
        public static int tw__tweet_dark_primary_text_color=0x7f07000d;
        public static int tw__tweet_light_container_bg_color=0x7f07000e;
        public static int tw__tweet_light_primary_text_color=0x7f07000f;
        public static int tw__tweet_media_preview_bg_color=0x7f070010;
    }
    public static final class dimen {
        public static int dgts__countdown_margin=0x7f060060;
        public static int dgts__country_code_margin_bottom=0x7f060061;
        public static int dgts__margin_bottom=0x7f060062;
        public static int dgts__margin_left=0x7f060063;
        public static int dgts__margin_right=0x7f060064;
        public static int dgts__padding_container=0x7f060065;
        public static int dgts__padding_title=0x7f060066;
        public static int dgts__permissions_margin_bottom=0x7f060067;
        public static int dgts__progress_bar_side_length=0x7f060068;
        public static int dgts__terms_text_size=0x7f060069;
        public static int dgts__title_text_size=0x7f06006a;
        public static int tw__btn_bar_margin_left=0x7f06004a;
        public static int tw__btn_bar_margin_right=0x7f06004b;
        public static int tw__card_font_size_medium=0x7f060000;
        public static int tw__card_font_size_small=0x7f060001;
        public static int tw__card_maximum_width=0x7f060002;
        public static int tw__card_radius_medium=0x7f060003;
        public static int tw__card_radius_small=0x7f060004;
        public static int tw__card_spacing_large=0x7f060005;
        public static int tw__card_spacing_medium=0x7f060006;
        public static int tw__card_spacing_small=0x7f060007;
        public static int tw__compact_tweet_action_bar_offset_left=0x7f060014;
        public static int tw__compact_tweet_attribution_line_margin_right=0x7f060015;
        public static int tw__compact_tweet_avatar_margin_left=0x7f060016;
        public static int tw__compact_tweet_avatar_margin_right=0x7f060017;
        public static int tw__compact_tweet_avatar_margin_top=0x7f060018;
        public static int tw__compact_tweet_container_bottom_separator=0x7f060019;
        public static int tw__compact_tweet_container_padding_top=0x7f06001a;
        public static int tw__compact_tweet_full_name_margin_top=0x7f06001b;
        public static int tw__compact_tweet_logo_margin_right=0x7f06001c;
        public static int tw__compact_tweet_logo_margin_top=0x7f06001d;
        public static int tw__compact_tweet_media_margin_bottom=0x7f06001e;
        public static int tw__compact_tweet_media_margin_right=0x7f06001f;
        public static int tw__compact_tweet_media_margin_top=0x7f060020;
        public static int tw__compact_tweet_retweeted_by_drawable_padding=0x7f060021;
        public static int tw__compact_tweet_retweeted_by_margin_bottom=0x7f060022;
        public static int tw__compact_tweet_retweeted_by_margin_left=0x7f060023;
        public static int tw__compact_tweet_retweeted_by_margin_top=0x7f060024;
        public static int tw__compact_tweet_screen_name_layout_width=0x7f060025;
        public static int tw__compact_tweet_screen_name_margin_bottom=0x7f060026;
        public static int tw__compact_tweet_screen_name_margin_top=0x7f060027;
        public static int tw__compact_tweet_screen_name_padding_left=0x7f060028;
        public static int tw__compact_tweet_text_margin_left=0x7f060029;
        public static int tw__compact_tweet_text_margin_right=0x7f06002a;
        public static int tw__compact_tweet_text_margin_top=0x7f06002b;
        public static int tw__compact_tweet_timestamp_margin_top=0x7f06002c;
        public static int tw__composer_avatar_size=0x7f060008;
        public static int tw__composer_char_count_height=0x7f060009;
        public static int tw__composer_close_size=0x7f06000a;
        public static int tw__composer_divider_height=0x7f06000b;
        public static int tw__composer_font_size_small=0x7f06000c;
        public static int tw__composer_logo_height=0x7f06000d;
        public static int tw__composer_logo_width=0x7f06000e;
        public static int tw__composer_spacing_large=0x7f06000f;
        public static int tw__composer_spacing_medium=0x7f060010;
        public static int tw__composer_spacing_small=0x7f060011;
        public static int tw__composer_tweet_btn_height=0x7f060012;
        public static int tw__composer_tweet_btn_radius=0x7f060013;
        public static int tw__gif_badge_padding=0x7f06002d;
        public static int tw__login_btn_drawable_padding=0x7f06004c;
        public static int tw__login_btn_height=0x7f06004d;
        public static int tw__login_btn_left_padding=0x7f06004e;
        public static int tw__login_btn_radius=0x7f06004f;
        public static int tw__login_btn_right_padding=0x7f060050;
        public static int tw__login_btn_text_size=0x7f060051;
        public static int tw__padding_permission_horizontal_container=0x7f060052;
        public static int tw__padding_permission_vertical_container=0x7f060053;
        public static int tw__permission_description_text_size=0x7f060054;
        public static int tw__permission_title_text_size=0x7f060055;
        public static int tw__seekbar_thumb_inner_padding=0x7f06002e;
        public static int tw__seekbar_thumb_outer_padding=0x7f06002f;
        public static int tw__seekbar_thumb_size=0x7f060030;
        public static int tw__text_size_large=0x7f060031;
        public static int tw__text_size_medium=0x7f060032;
        public static int tw__text_size_small=0x7f060033;
        public static int tw__tweet_action_bar_offset_bottom=0x7f060034;
        public static int tw__tweet_action_bar_offset_left=0x7f060035;
        public static int tw__tweet_action_button_margin_top=0x7f060036;
        public static int tw__tweet_action_button_spacing=0x7f060037;
        public static int tw__tweet_action_heart_size=0x7f060038;
        public static int tw__tweet_action_share_padding=0x7f060039;
        public static int tw__tweet_avatar_margin_left=0x7f06003a;
        public static int tw__tweet_avatar_margin_right=0x7f06003b;
        public static int tw__tweet_avatar_margin_top=0x7f06003c;
        public static int tw__tweet_avatar_size=0x7f06003d;
        public static int tw__tweet_container_bottom_separator=0x7f06003e;
        public static int tw__tweet_container_padding_top=0x7f06003f;
        public static int tw__tweet_full_name_margin_top=0x7f060040;
        public static int tw__tweet_logo_margin_right=0x7f060041;
        public static int tw__tweet_logo_margin_top=0x7f060042;
        public static int tw__tweet_media_aspect_ratio=0x7f060043;
        public static int tw__tweet_media_badge_margin=0x7f060044;
        public static int tw__tweet_retweeted_by_drawable_padding=0x7f060045;
        public static int tw__tweet_retweeted_by_margin_bottom=0x7f060046;
        public static int tw__tweet_retweeted_by_margin_left=0x7f060047;
        public static int tw__tweet_retweeted_by_margin_top=0x7f060048;
        public static int tw__tweet_screen_name_margin_bottom=0x7f060049;
        public static int tw__tweet_screen_name_margin_top=0x7f060056;
        public static int tw__tweet_text_margin_left=0x7f060057;
        public static int tw__tweet_text_margin_right=0x7f060058;
        public static int tw__tweet_text_margin_top=0x7f060059;
        public static int tw__tweet_timestamp_margin_top=0x7f06005a;
        public static int tw__tweet_timestamp_padding_left=0x7f06005b;
        public static int tw__tweet_verified_check_padding_left=0x7f06005c;
        public static int tw__tweet_verified_margin_bottom=0x7f06005d;
        public static int tw__video_control_height=0x7f06005e;
        public static int tw__video_control_text_size=0x7f06005f;
    }
    public static final class drawable {
        public static int dgts__addressbook_header=0x7f020000;
        public static int dgts__digits_btn=0x7f020001;
        public static int dgts__digits_btn_default=0x7f020002;
        public static int dgts__digits_btn_pressed=0x7f020003;
        public static int dgts__ic_success=0x7f020004;
        public static int dgts__login_header=0x7f020005;
        public static int dgts__logo=0x7f020006;
        public static int dgts__logo_name=0x7f020007;
        public static int dgts__spinner_dark=0x7f020008;
        public static int dgts__spinner_light=0x7f020009;
        public static int progress_dark=0x7f02000a;
        public static int progress_light=0x7f02000b;
        public static int tw__action_heart_off_default=0x7f02000c;
        public static int tw__action_heart_on_default=0x7f02000d;
        public static int tw__app_info_layout_border=0x7f02000e;
        public static int tw__bg_media_badge=0x7f02000f;
        public static int tw__btn_composer_tweet=0x7f020010;
        public static int tw__composer_close=0x7f020011;
        public static int tw__composer_logo_blue=0x7f020012;
        public static int tw__composer_logo_white=0x7f020013;
        public static int tw__gif_badge=0x7f020014;
        public static int tw__heart_animation_detail_60fps_00000=0x7f020015;
        public static int tw__heart_animation_detail_60fps_00001=0x7f020016;
        public static int tw__heart_animation_detail_60fps_00002=0x7f020017;
        public static int tw__heart_animation_detail_60fps_00003=0x7f020018;
        public static int tw__heart_animation_detail_60fps_00004=0x7f020019;
        public static int tw__heart_animation_detail_60fps_00005=0x7f02001a;
        public static int tw__heart_animation_detail_60fps_00006=0x7f02001b;
        public static int tw__heart_animation_detail_60fps_00007=0x7f02001c;
        public static int tw__heart_animation_detail_60fps_00008=0x7f02001d;
        public static int tw__heart_animation_detail_60fps_00009=0x7f02001e;
        public static int tw__heart_animation_detail_60fps_00010=0x7f02001f;
        public static int tw__heart_animation_detail_60fps_00011=0x7f020020;
        public static int tw__heart_animation_detail_60fps_00012=0x7f020021;
        public static int tw__heart_animation_detail_60fps_00013=0x7f020022;
        public static int tw__heart_animation_detail_60fps_00014=0x7f020023;
        public static int tw__heart_animation_detail_60fps_00015=0x7f020024;
        public static int tw__heart_animation_detail_60fps_00016=0x7f020025;
        public static int tw__heart_animation_detail_60fps_00017=0x7f020026;
        public static int tw__heart_animation_detail_60fps_00018=0x7f020027;
        public static int tw__heart_animation_detail_60fps_00019=0x7f020028;
        public static int tw__heart_animation_detail_60fps_00020=0x7f020029;
        public static int tw__heart_animation_detail_60fps_00021=0x7f02002a;
        public static int tw__heart_animation_detail_60fps_00022=0x7f02002b;
        public static int tw__heart_animation_detail_60fps_00023=0x7f02002c;
        public static int tw__heart_animation_detail_60fps_00024=0x7f02002d;
        public static int tw__heart_animation_detail_60fps_00025=0x7f02002e;
        public static int tw__heart_animation_detail_60fps_00026=0x7f02002f;
        public static int tw__heart_animation_detail_60fps_00027=0x7f020030;
        public static int tw__heart_animation_detail_60fps_00028=0x7f020031;
        public static int tw__heart_animation_detail_60fps_00029=0x7f020032;
        public static int tw__heart_animation_detail_60fps_00030=0x7f020033;
        public static int tw__heart_animation_detail_60fps_00031=0x7f020034;
        public static int tw__heart_animation_detail_60fps_00032=0x7f020035;
        public static int tw__heart_animation_detail_60fps_00033=0x7f020036;
        public static int tw__heart_animation_detail_60fps_00034=0x7f020037;
        public static int tw__heart_animation_detail_60fps_00035=0x7f020038;
        public static int tw__heart_animation_detail_60fps_00036=0x7f020039;
        public static int tw__heart_animation_detail_60fps_00037=0x7f02003a;
        public static int tw__heart_animation_detail_60fps_00038=0x7f02003b;
        public static int tw__heart_animation_detail_60fps_00039=0x7f02003c;
        public static int tw__heart_animation_detail_60fps_00040=0x7f02003d;
        public static int tw__heart_animation_detail_60fps_00041=0x7f02003e;
        public static int tw__heart_animation_detail_60fps_00042=0x7f02003f;
        public static int tw__heart_animation_detail_60fps_00043=0x7f020040;
        public static int tw__heart_animation_detail_60fps_00044=0x7f020041;
        public static int tw__heart_animation_detail_60fps_00045=0x7f020042;
        public static int tw__heart_animation_detail_60fps_00046=0x7f020043;
        public static int tw__heart_animation_detail_60fps_00047=0x7f020044;
        public static int tw__heart_animation_detail_60fps_00048=0x7f020045;
        public static int tw__heart_animation_detail_60fps_00049=0x7f020046;
        public static int tw__heart_animation_detail_60fps_00050=0x7f020047;
        public static int tw__heart_animation_detail_60fps_00051=0x7f020048;
        public static int tw__heart_animation_detail_60fps_00052=0x7f020049;
        public static int tw__heart_animation_detail_60fps_00053=0x7f02004a;
        public static int tw__heart_animation_detail_60fps_00054=0x7f02004b;
        public static int tw__heart_animation_detail_60fps_00055=0x7f02004c;
        public static int tw__heart_animation_detail_60fps_00056=0x7f02004d;
        public static int tw__heart_animation_detail_60fps_00057=0x7f02004e;
        public static int tw__heart_animation_detail_60fps_00058=0x7f02004f;
        public static int tw__heart_animation_detail_60fps_00059=0x7f020050;
        public static int tw__ic_gif_badge=0x7f020051;
        public static int tw__ic_inline_share=0x7f020052;
        public static int tw__ic_logo_blue=0x7f020053;
        /**    <public type="drawable" name="tw__transparent" id="0x7f0200cf" />  
         */
        public static int tw__ic_logo_default=0x7f0200af;
        public static int tw__ic_logo_white=0x7f020054;
        public static int tw__ic_play_default=0x7f020055;
        public static int tw__ic_play_pressed=0x7f020056;
        public static int tw__ic_retweet_dark=0x7f020057;
        public static int tw__ic_retweet_light=0x7f020058;
        public static int tw__ic_seekbar_bg=0x7f020059;
        public static int tw__ic_seekbar_progress_bg=0x7f02005a;
        public static int tw__ic_seekbar_secondary_bg=0x7f02005b;
        public static int tw__ic_tweet_photo_error_dark=0x7f02005c;
        public static int tw__ic_tweet_photo_error_light=0x7f02005d;
        public static int tw__ic_tweet_verified=0x7f02005e;
        public static int tw__ic_video_pause=0x7f02005f;
        public static int tw__ic_video_pause_pressed=0x7f020060;
        public static int tw__ic_video_play=0x7f020061;
        public static int tw__ic_video_play_pressed=0x7f020062;
        public static int tw__ic_video_replay=0x7f020063;
        public static int tw__ic_video_replay_pressed=0x7f020064;
        public static int tw__install_button_border=0x7f020065;
        public static int tw__like_action=0x7f020066;
        public static int tw__login_btn=0x7f0200c3;
        public static int tw__login_btn_default=0x7f0200c4;
        public static int tw__login_btn_default_light=0x7f0200c5;
        public static int tw__login_btn_disabled=0x7f0200c6;
        public static int tw__login_btn_light=0x7f0200c7;
        public static int tw__login_btn_pressed=0x7f0200c8;
        public static int tw__login_btn_pressed_light=0x7f0200c9;
        public static int tw__login_btn_text_color_light=0x7f0200ca;
        public static int tw__player_overlay=0x7f0200cb;
        public static int tw__seekbar_thumb=0x7f0200cc;
        public static int tw__share_action=0x7f0200cd;
        public static int tw__share_email_header=0x7f020067;
        public static int tw__transparent=0x7f020068;
        public static int tw__video_pause_btn=0x7f020069;
        public static int tw__video_play_btn=0x7f02006a;
        public static int tw__video_replay_btn=0x7f02006b;
        public static int tw__video_seekbar=0x7f02006c;
    }
    public static final class id {
        public static int bottom_separator=0x7f0c0109;
        public static int dgts__callMeButton=0x7f0c00cd;
        public static int dgts__confirmationEditText=0x7f0c00c9;
        public static int dgts__countdownTimer=0x7f0c00ce;
        public static int dgts__countryCode=0x7f0c00da;
        public static int dgts__createAccount=0x7f0c00cb;
        public static int dgts__dismiss_button=0x7f0c00d7;
        public static int dgts__editPhoneNumber=0x7f0c00c8;
        public static int dgts__error_text=0x7f0c00d6;
        public static int dgts__error_title=0x7f0c00d5;
        public static int dgts__find_your_friends=0x7f0c00d1;
        public static int dgts__header_image=0x7f0c00d0;
        public static int dgts__logo=0x7f0c00d9;
        public static int dgts__logo_icon=0x7f0c00de;
        public static int dgts__logo_name=0x7f0c00df;
        public static int dgts__not_now=0x7f0c00d3;
        public static int dgts__okay=0x7f0c00d4;
        public static int dgts__phoneNumberEditText=0x7f0c00db;
        public static int dgts__resendConfirmationButton=0x7f0c00cc;
        public static int dgts__sendCodeButton=0x7f0c00dc;
        public static int dgts__state_button=0x7f0c00e0;
        public static int dgts__state_progress=0x7f0c00e1;
        public static int dgts__state_success=0x7f0c00e2;
        public static int dgts__termsText=0x7f0c00dd;
        public static int dgts__termsTextCreateAccount=0x7f0c00cf;
        public static int dgts__titleText=0x7f0c00c7;
        public static int dgts__try_another_phone=0x7f0c00d8;
        public static int dgts__upload_contacts=0x7f0c00d2;
        public static int height=0x7f0c0005;
        public static int imageView=0x7f0c00c3;
        public static int image_view=0x7f0c00f9;
        public static int strut=0x7f0c00ca;
        public static int tw__allow_btn=0x7f0c00c6;
        public static int tw__app_image=0x7f0c00e8;
        public static int tw__app_info_layout=0x7f0c00e9;
        public static int tw__app_install_button=0x7f0c00ea;
        public static int tw__app_name=0x7f0c00eb;
        public static int tw__app_store_name=0x7f0c00ec;
        public static int tw__author_attribution=0x7f0c010a;
        public static int tw__author_avatar=0x7f0c00f0;
        public static int tw__card_view=0x7f0c00f4;
        public static int tw__char_count=0x7f0c00f7;
        public static int tw__composer_close=0x7f0c00ee;
        public static int tw__composer_header=0x7f0c00ed;
        public static int tw__composer_profile_divider=0x7f0c00f1;
        public static int tw__composer_scroll_view=0x7f0c00f2;
        public static int tw__composer_toolbar=0x7f0c00f6;
        public static int tw__composer_toolbar_divider=0x7f0c00f5;
        public static int tw__composer_view=0x7f0c00e6;
        public static int tw__edit_tweet=0x7f0c00f3;
        public static int tw__gif_badge=0x7f0c00fa;
        public static int tw__not_now_btn=0x7f0c00c5;
        public static int tw__post_tweet=0x7f0c00f8;
        public static int tw__share_email_desc=0x7f0c00e7;
        public static int tw__spinner=0x7f0c00c2;
        public static int tw__tweet_action_bar=0x7f0c00e3;
        public static int tw__tweet_author_avatar=0x7f0c0103;
        public static int tw__tweet_author_full_name=0x7f0c0104;
        public static int tw__tweet_author_screen_name=0x7f0c0106;
        public static int tw__tweet_author_verified=0x7f0c0105;
        public static int tw__tweet_like_button=0x7f0c00e4;
        public static int tw__tweet_media=0x7f0c0100;
        public static int tw__tweet_media_badge=0x7f0c0101;
        public static int tw__tweet_media_container=0x7f0c00ff;
        public static int tw__tweet_retweeted_by=0x7f0c0102;
        public static int tw__tweet_share_button=0x7f0c00e5;
        public static int tw__tweet_text=0x7f0c0108;
        public static int tw__tweet_timestamp=0x7f0c0107;
        public static int tw__tweet_view=0x7f0c00fe;
        public static int tw__twitter_logo=0x7f0c00ef;
        public static int tw__video_duration=0x7f0c00fb;
        public static int tw__web_view=0x7f0c00c1;
        public static int video_control_view=0x7f0c00fd;
        public static int video_view=0x7f0c00fc;
        public static int width=0x7f0c0006;
    }
    public static final class layout {
        public static int dgts__activity_confirmation=0x7f030000;
        public static int dgts__activity_contacts=0x7f030001;
        public static int dgts__activity_failure=0x7f030002;
        public static int dgts__activity_phone_number=0x7f030003;
        public static int dgts__activity_pin_code=0x7f030004;
        public static int dgts__country_row=0x7f030005;
        public static int dgts__state_button=0x7f030006;
        public static int tw__action_bar=0x7f030007;
        public static int tw__activity_composer=0x7f030008;
        public static int tw__activity_oauth=0x7f030043;
        public static int tw__activity_share_email=0x7f030044;
        public static int tw__app_card=0x7f030009;
        public static int tw__composer_view=0x7f03000a;
        public static int tw__gallery_activity=0x7f03000b;
        public static int tw__media_badge=0x7f03000c;
        public static int tw__player_activity=0x7f03000d;
        public static int tw__tweet=0x7f03000e;
        public static int tw__tweet_compact=0x7f03000f;
    }
    public static final class plurals {
        public static int tw__time_hours=0x7f040000;
        public static int tw__time_mins=0x7f040001;
        public static int tw__time_secs=0x7f040002;
    }
    public static final class raw {
        public static int tw__cacerts=0x7f050000;
    }
    public static final class string {
        public static int dgts__call_me=0x7f08000d;
        public static int dgts__calling=0x7f08000e;
        public static int dgts__confirmation_code=0x7f08000f;
        public static int dgts__confirmation_edit_hint=0x7f080010;
        public static int dgts__confirmation_error=0x7f080011;
        public static int dgts__confirmation_error_alternative=0x7f080012;
        public static int dgts__confirmation_expired=0x7f080013;
        public static int dgts__continue=0x7f080014;
        public static int dgts__country_spinner_format=0x7f08003b;
        public static int dgts__create_account=0x7f08003c;
        public static int dgts__digits_com_settings_url=0x7f08003d;
        public static int dgts__digits_com_url=0x7f08003e;
        public static int dgts__digits_logo_desc=0x7f080015;
        public static int dgts__digits_logo_name_desc=0x7f080016;
        public static int dgts__dismiss=0x7f080017;
        public static int dgts__done=0x7f080018;
        public static int dgts__email_request_edit_hint=0x7f080019;
        public static int dgts__email_request_title=0x7f08001a;
        public static int dgts__find_your_friends=0x7f08001b;
        public static int dgts__image_header_description=0x7f08001c;
        public static int dgts__invalid_email=0x7f08001d;
        public static int dgts__login_digits_text=0x7f08001e;
        public static int dgts__network_error=0x7f08001f;
        public static int dgts__not_now=0x7f080020;
        public static int dgts__okay=0x7f080021;
        public static int dgts__phone_number_edit_hint=0x7f080022;
        public static int dgts__phone_number_text=0x7f080023;
        public static int dgts__pin_code_verification_title=0x7f080024;
        public static int dgts__resend_confirmation_button_code=0x7f080025;
        public static int dgts__resend_confirmation_text=0x7f080026;
        public static int dgts__send_confirmation_code=0x7f08003f;
        public static int dgts__sending=0x7f080027;
        public static int dgts__success_desc=0x7f080028;
        public static int dgts__terms_email_request=0x7f080040;
        public static int dgts__terms_text=0x7f080037;
        public static int dgts__terms_text_call_me=0x7f080038;
        public static int dgts__terms_text_create=0x7f080039;
        public static int dgts__terms_text_sign_in=0x7f08003a;
        public static int dgts__terms_text_updated=0x7f080041;
        public static int dgts__try_again=0x7f080029;
        public static int dgts__try_again_confirmation=0x7f08002a;
        public static int dgts__try_again_email=0x7f08002b;
        public static int dgts__try_again_phone_number=0x7f08002c;
        public static int dgts__try_another_phone=0x7f08002d;
        public static int dgts__twitter_cookies_policy_url=0x7f080042;
        public static int dgts__twitter_privacy_url=0x7f080043;
        public static int dgts__twitter_tos_url=0x7f080044;
        public static int dgts__unsupported_operator_error=0x7f08002e;
        public static int dgts__upload_contacts=0x7f08002f;
        public static int dgts__verification_code=0x7f080030;
        public static int dgts_pin_code_terms=0x7f080031;
        public static int kit_name=0x7f080167;
        public static int tw__allow_btn_txt=0x7f08012b;
        public static int tw__composer_hint=0x7f080032;
        public static int tw__install=0x7f080033;
        public static int tw__like_tweet=0x7f080000;
        public static int tw__liked_tweet=0x7f080001;
        public static int tw__loading_tweet=0x7f080002;
        public static int tw__login_btn_txt=0x7f08012c;
        public static int tw__max_tweet_chars=0x7f080034;
        public static int tw__not_now_btn_txt=0x7f08012d;
        public static int tw__pause=0x7f080003;
        public static int tw__play=0x7f080004;
        public static int tw__play_store=0x7f080035;
        public static int tw__post_tweet=0x7f080036;
        public static int tw__relative_date_format_long=0x7f080005;
        public static int tw__relative_date_format_short=0x7f080006;
        public static int tw__replay=0x7f080007;
        public static int tw__retweeted_by_format=0x7f080008;
        public static int tw__share_content_format=0x7f080009;
        public static int tw__share_email_desc=0x7f08012e;
        public static int tw__share_email_title=0x7f08012f;
        public static int tw__share_subject_format=0x7f08000a;
        public static int tw__share_tweet=0x7f08000b;
        public static int tw__tweet_content_description=0x7f08000c;
    }
    public static final class style {
        public static int ComposerDark=0x7f090000;
        public static int ComposerLight=0x7f090001;
        public static int Digits_default=0x7f09003a;
        public static int MediaTheme=0x7f09000e;
        public static int dgts__ButtonText=0x7f09003b;
        public static int dgts__Container=0x7f09003c;
        public static int dgts__CountDownTimer=0x7f09003d;
        public static int dgts__EnterConfirmationCodeTitle=0x7f09003e;
        public static int dgts__HeaderMargin=0x7f09003f;
        public static int dgts__Terms=0x7f090040;
        public static int dgts__Title=0x7f090041;
        public static int tw__AttributionText=0x7f09000f;
        public static int tw__Badge=0x7f090010;
        public static int tw__Badge_Gif=0x7f090011;
        public static int tw__Badge_VideoDuration=0x7f090012;
        public static int tw__Button=0x7f09001b;
        public static int tw__Button_Light=0x7f09001c;
        public static int tw__ButtonBar=0x7f09001d;
        public static int tw__CardAppInfoLayout=0x7f090002;
        public static int tw__CardAppName=0x7f090003;
        public static int tw__CardAppStoreName=0x7f090004;
        public static int tw__CardInstallButton=0x7f090005;
        public static int tw__CompactAttributionLine=0x7f090013;
        public static int tw__CompactTweetContainer=0x7f090014;
        public static int tw__ComposerAvatar=0x7f090006;
        public static int tw__ComposerCharCount=0x7f090007;
        public static int tw__ComposerCharCountOverflow=0x7f090008;
        public static int tw__ComposerClose=0x7f090009;
        public static int tw__ComposerDivider=0x7f09000a;
        public static int tw__ComposerToolbar=0x7f09000b;
        public static int tw__ComposerTweetButton=0x7f09000c;
        public static int tw__EditTweet=0x7f09000d;
        public static int tw__Permission_Container=0x7f09001e;
        public static int tw__Permission_Description=0x7f09001f;
        public static int tw__Permission_Title=0x7f090020;
        public static int tw__TweetActionButton=0x7f090015;
        public static int tw__TweetActionButton_Heart=0x7f090016;
        public static int tw__TweetActionButton_Share=0x7f090017;
        public static int tw__TweetActionButtonBar=0x7f090018;
        public static int tw__TweetActionButtonBar_Compact=0x7f090019;
        public static int tw__TweetAvatar=0x7f09001a;
        public static int tw__TweetAvatar_Compact=0x7f090021;
        public static int tw__TweetBadge=0x7f090022;
        public static int tw__TweetContainer=0x7f090023;
        public static int tw__TweetDarkStyle=0x7f090024;
        public static int tw__TweetDarkWithActionsStyle=0x7f090025;
        public static int tw__TweetFillWidth=0x7f090026;
        public static int tw__TweetFullName=0x7f090027;
        public static int tw__TweetFullName_Compact=0x7f090028;
        public static int tw__TweetFullNameBase=0x7f090029;
        public static int tw__TweetLightStyle=0x7f09002a;
        public static int tw__TweetLightWithActionsStyle=0x7f09002b;
        public static int tw__TweetMedia=0x7f09002c;
        public static int tw__TweetMediaContainer=0x7f09002d;
        public static int tw__TweetMediaContainer_Compact=0x7f09002e;
        public static int tw__TweetRetweetedBy=0x7f09002f;
        public static int tw__TweetRetweetedBy_Compact=0x7f090030;
        public static int tw__TweetScreenName=0x7f090031;
        public static int tw__TweetScreenName_Compact=0x7f090032;
        public static int tw__TweetText=0x7f090033;
        public static int tw__TweetText_Compact=0x7f090034;
        public static int tw__TweetTimestamp=0x7f090035;
        public static int tw__TweetTimestamp_Compact=0x7f090036;
        public static int tw__TweetVerifiedCheck=0x7f090037;
        public static int tw__TwitterLogo=0x7f090038;
        public static int tw__TwitterLogo_Compact=0x7f090039;
    }
    public static final class styleable {
        /** Attributes that can be used with a StateButton.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #StateButton_dgts__StateButtonStyle com.twitter.sdk.android.tweetcomposer:dgts__StateButtonStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #StateButton_finishStateText com.twitter.sdk.android.tweetcomposer:finishStateText}</code></td><td></td></tr>
           <tr><td><code>{@link #StateButton_progressStateText com.twitter.sdk.android.tweetcomposer:progressStateText}</code></td><td></td></tr>
           <tr><td><code>{@link #StateButton_startStateText com.twitter.sdk.android.tweetcomposer:startStateText}</code></td><td></td></tr>
           </table>
           @see #StateButton_dgts__StateButtonStyle
           @see #StateButton_finishStateText
           @see #StateButton_progressStateText
           @see #StateButton_startStateText
         */
        public static final int[] StateButton = {
            0x7f01000d, 0x7f01000e, 0x7f01000f, 0x7f010010
        };
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#dgts__StateButtonStyle}
          attribute's value can be found in the {@link #StateButton} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.twitter.sdk.android.tweetcomposer:dgts__StateButtonStyle
        */
        public static int StateButton_dgts__StateButtonStyle = 3;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#finishStateText}
          attribute's value can be found in the {@link #StateButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:finishStateText
        */
        public static int StateButton_finishStateText = 0;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#progressStateText}
          attribute's value can be found in the {@link #StateButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:progressStateText
        */
        public static int StateButton_progressStateText = 1;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#startStateText}
          attribute's value can be found in the {@link #StateButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:startStateText
        */
        public static int StateButton_startStateText = 2;
        /** Attributes that can be used with a ToggleImageButton.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ToggleImageButton_contentDescriptionOff com.twitter.sdk.android.tweetcomposer:contentDescriptionOff}</code></td><td></td></tr>
           <tr><td><code>{@link #ToggleImageButton_contentDescriptionOn com.twitter.sdk.android.tweetcomposer:contentDescriptionOn}</code></td><td></td></tr>
           <tr><td><code>{@link #ToggleImageButton_state_toggled_on com.twitter.sdk.android.tweetcomposer:state_toggled_on}</code></td><td></td></tr>
           <tr><td><code>{@link #ToggleImageButton_toggleOnClick com.twitter.sdk.android.tweetcomposer:toggleOnClick}</code></td><td></td></tr>
           </table>
           @see #ToggleImageButton_contentDescriptionOff
           @see #ToggleImageButton_contentDescriptionOn
           @see #ToggleImageButton_state_toggled_on
           @see #ToggleImageButton_toggleOnClick
         */
        public static final int[] ToggleImageButton = {
            0x7f010001, 0x7f010002, 0x7f010003, 0x7f010004
        };
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#contentDescriptionOff}
          attribute's value can be found in the {@link #ToggleImageButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:contentDescriptionOff
        */
        public static int ToggleImageButton_contentDescriptionOff = 2;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#contentDescriptionOn}
          attribute's value can be found in the {@link #ToggleImageButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:contentDescriptionOn
        */
        public static int ToggleImageButton_contentDescriptionOn = 1;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#state_toggled_on}
          attribute's value can be found in the {@link #ToggleImageButton} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:state_toggled_on
        */
        public static int ToggleImageButton_state_toggled_on = 0;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#toggleOnClick}
          attribute's value can be found in the {@link #ToggleImageButton} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:toggleOnClick
        */
        public static int ToggleImageButton_toggleOnClick = 3;
        /** Attributes that can be used with a tw__AspectRatioImageView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #tw__AspectRatioImageView_tw__image_aspect_ratio com.twitter.sdk.android.tweetcomposer:tw__image_aspect_ratio}</code></td><td></td></tr>
           <tr><td><code>{@link #tw__AspectRatioImageView_tw__image_dimension_to_adjust com.twitter.sdk.android.tweetcomposer:tw__image_dimension_to_adjust}</code></td><td></td></tr>
           </table>
           @see #tw__AspectRatioImageView_tw__image_aspect_ratio
           @see #tw__AspectRatioImageView_tw__image_dimension_to_adjust
         */
        public static final int[] tw__AspectRatioImageView = {
            0x7f01002c, 0x7f01002d
        };
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#tw__image_aspect_ratio}
          attribute's value can be found in the {@link #tw__AspectRatioImageView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:tw__image_aspect_ratio
        */
        public static int tw__AspectRatioImageView_tw__image_aspect_ratio = 0;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#tw__image_dimension_to_adjust}
          attribute's value can be found in the {@link #tw__AspectRatioImageView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>height</code></td><td>0</td><td></td></tr>
<tr><td><code>width</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.twitter.sdk.android.tweetcomposer:tw__image_dimension_to_adjust
        */
        public static int tw__AspectRatioImageView_tw__image_dimension_to_adjust = 1;
        /** Attributes that can be used with a tw__TweetView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #tw__TweetView_tw__action_color com.twitter.sdk.android.tweetcomposer:tw__action_color}</code></td><td></td></tr>
           <tr><td><code>{@link #tw__TweetView_tw__action_highlight_color com.twitter.sdk.android.tweetcomposer:tw__action_highlight_color}</code></td><td></td></tr>
           <tr><td><code>{@link #tw__TweetView_tw__container_bg_color com.twitter.sdk.android.tweetcomposer:tw__container_bg_color}</code></td><td></td></tr>
           <tr><td><code>{@link #tw__TweetView_tw__primary_text_color com.twitter.sdk.android.tweetcomposer:tw__primary_text_color}</code></td><td></td></tr>
           <tr><td><code>{@link #tw__TweetView_tw__tweet_actions_enabled com.twitter.sdk.android.tweetcomposer:tw__tweet_actions_enabled}</code></td><td></td></tr>
           <tr><td><code>{@link #tw__TweetView_tw__tweet_id com.twitter.sdk.android.tweetcomposer:tw__tweet_id}</code></td><td></td></tr>
           </table>
           @see #tw__TweetView_tw__action_color
           @see #tw__TweetView_tw__action_highlight_color
           @see #tw__TweetView_tw__container_bg_color
           @see #tw__TweetView_tw__primary_text_color
           @see #tw__TweetView_tw__tweet_actions_enabled
           @see #tw__TweetView_tw__tweet_id
         */
        public static final int[] tw__TweetView = {
            0x7f010005, 0x7f010006, 0x7f010007, 0x7f010008,
            0x7f010009, 0x7f01000a
        };
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#tw__action_color}
          attribute's value can be found in the {@link #tw__TweetView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:tw__action_color
        */
        public static int tw__TweetView_tw__action_color = 3;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#tw__action_highlight_color}
          attribute's value can be found in the {@link #tw__TweetView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:tw__action_highlight_color
        */
        public static int tw__TweetView_tw__action_highlight_color = 4;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#tw__container_bg_color}
          attribute's value can be found in the {@link #tw__TweetView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:tw__container_bg_color
        */
        public static int tw__TweetView_tw__container_bg_color = 1;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#tw__primary_text_color}
          attribute's value can be found in the {@link #tw__TweetView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:tw__primary_text_color
        */
        public static int tw__TweetView_tw__primary_text_color = 2;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#tw__tweet_actions_enabled}
          attribute's value can be found in the {@link #tw__TweetView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:tw__tweet_actions_enabled
        */
        public static int tw__TweetView_tw__tweet_actions_enabled = 5;
        /**
          <p>This symbol is the offset where the {@link com.twitter.sdk.android.tweetcomposer.R.attr#tw__tweet_id}
          attribute's value can be found in the {@link #tw__TweetView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.twitter.sdk.android.tweetcomposer:tw__tweet_id
        */
        public static int tw__TweetView_tw__tweet_id = 0;
    };
}
